#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another pags

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service start nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo rm /var/www/html/index.nginx-debian.html
sudo sed -i '/\[::\]:80 default_server/ a \\n\trewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
