#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd.
FILENAME="/etc/passwd"
while IFS=: read -r username password user_id group_id user_id_info homedir cmdshell
do
  echo "The user $username is part of the $group_id gang, lives in $homedir and rides $cmdshell. $user_id's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < $FILENAME
