#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
x=1
while [ $x -le 20 ]
do
    if [ $x = 5 ]
    then
	echo "bad luck from China"
    elif [ $x = 10 ]
    then
	 echo "bad luck from Japan"
    elif [ $x = 18 ]
    then
	echo "bad luck from Italy"
    fi
    echo $x
    x=$(( x + 1 ))
done
